### PR TITLE
fix: Socket leak on error

### LINKED ISSUE #20: keep generating TCP connections with CLOSE_WAIT state
For all general issues, please provide the following details for fast resolution:

- Version: logstash 6.5.3, logstash-input-websocket 4.0.4
- Operating System: Ubuntu 16.04.5 LTS
- Config File (if you have sensitive info, please remove it):
input {
    websocket {
        mode => "client"
        url => "ws://xxxxxxxxxxxxxxxxxxxxx:80/app?token=yyyyyyyyyyyyyyyyyyy#"
    }
}

- Steps to Reproduce:
I am using websocket input to get data from a remote websocket server. However, the number of TCP connections with CLOSE_WAIT state keep increasing if there is exception thrown (e.g, the remote server unreachable for a while). 
1. check /var/log/logstash/logstash-plain.log:
[WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x2a9b0bf5>>}
[WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x6d4d385c>>}
[WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x2c03c447>>}
................

2. check the tcp connection:
netstat -ntp
Proto Recv-Q Send-Q Local Address                 Foreign Address                 State       PID/Program name
tcp6       1      0  <local_server_IP>:56712      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:49290      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:51528      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:59730      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:46522      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
......................

3. finally the number of CLOSE_WAIT connections will be many (e.g 15000+), and logstash stops working due to excessive number of connections. I have to restart the logstash service.

I wonder if there is a bug in the current retry logic? Thanks.

### LINKED ISSUE #21: Don't assume that FTW::Agent.websocket! always returns a FTW::WebSocket object
The code assumes that FTW::Agent.websocket! always returns a FTW::WebSocket object that we can call `each` on, but that's only true if the websocket handshake is successful. Because of this flawed assumption we get this, which is not only ugly but also hides the actual response that might contain information useful for debugging:

    [WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #FTW::Response:0x2c03c447>}

This was originally seen and reported in #20.

### PR DESCRIPTION
**Pull request by stevenh**
Fix sockets being leaked if we get any errors by calling agent.shutdown to close all active connections.

Improve connection handling adding support for backoff and connection termination on logstash shutdown.

New configuration options added:
* retry_initial
* retry_max
* retry_reset
* debug_status

Also:
* Remove unused socket require.
* Clean up logging.
* Bump version to 4.0.5

Fixes #20 
Fixes #21

### CODE REVIEW

**Comment by stevenh** [comment]
In the hope it will be helpful for others I had extreme difficulty getting to the stage I could run the rspec tests for this repo so here's some hints:
1.  ubuntu 18 LTS jruby in apt is broken don't us it, you need `9.2` or above otherwise you will just get an error trying to run `jruby -S bundle install`
```
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant SNAKEYAML_VERSION
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant ANY
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant UTF8
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant UTF16LE
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant UTF16BE
/usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter
           require at org/jruby/RubyKernel.java:956
           require at /usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
            <main> at /usr/share/jruby/lib/ruby/stdlib/yaml.rb:6
           require at org/jruby/RubyKernel.java:956
           require at /usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
            (root) at /usr/share/jruby/lib/ruby/stdlib/rubygems.rb:1
         load_yaml at /usr/share/jruby/lib/ruby/stdlib/rubygems.rb:701
         load_file at /usr/share/jruby/lib/ruby/stdlib/rubygems/config_file.rb:340
        initialize at /usr/share/jruby/lib/ruby/stdlib/rubygems/config_file.rb:202
  do_configuration at /usr/share/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:75
            <main> at /usr/share/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:40
              load at org/jruby/RubyKernel.java:974
            <main> at /usr/share/jruby/bin/gem:4
```
The latest version of jruby can be downloaded here:
[https://www.jruby.org/download](https://www.jruby.org/download)

2. This repo uses a logstash 5.6 which only supports java 8, if you use a later version you'll get the following error.
```
An error occurred while loading ./spec/inputs/websocket_spec.rb.
Failure/Error: require "logstash/devutils/rspec/spec_helper"

NameError:
  missing class name (`org.logstash.common.DeadLetterQueueFactory')
# ./spec/inputs/websocket_spec.rb:1:in `<main>'
```

In our case we not only got connections in `CLOSE_WAIT` but also in `ESTABLISHED` so many it ran the machine out of file handles, breaking everything.

File: lib/logstash/inputs/websocket.rb [hunk 1]
```diff
@@ -13,32 +12,110 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
+  rescue EOFError => e
+    @logger.debug("Run error ",
+                 :exception => e,
+                 :url => @url_safe,
+                 :retry => @interval) unless stop?
+  rescue => e
+    @logger.warn("Run error ",
+                 :exception => e,
+                 :url => @url_safe,
+                 :retry => @interval) unless stop?
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: Is there any particular point with the special handling of EOFError given the subsequent catch-all rescue block?

File: lib/logstash/inputs/websocket.rb [hunk 2]
```diff
@@ -13,32 +12,110 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
+      if r.status != 404 || @warn_404
+        @logger.warn("Connect failed",
+                     :status => r.status_line,
+                     :url => @url_safe,
+                     :retry => @interval) unless stop?
+      else
+        @logger.debug("Connect failed",
+                     :status => r.status_line,
+                     :url => @url_safe,
+                     :retry => @interval) unless stop?
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: Why should 404s be treated differently that other status codes? Under which circumstances would one set `warn_404` to false?

File: lib/logstash/inputs/websocket.rb [hunk 3]
```diff
@@ -13,32 +12,110 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
+  end # def run_single
+
+  def backoff()
+    if @processed > @retry_reset
+      @interval = @retry_initial
+    elsif @interval * 2 >= @retry_max
+      @interval = @retry_max
+    else
+      @interval = @interval * 2
+    end
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: Nit: Equivalent and IMHO more idiomatic:

```ruby
else
  @interval = [@interval * 2, @retry_max].min
end
```

File: lib/logstash/inputs/websocket.rb [hunk 4]
```diff
@@ -13,32 +12,110 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
 
+  # The retry interval connections start with.
+  config :retry_initial, :validate => :number, :default => 1
+
+  # The maximum retry interval backoff will increase too.
+  config :retry_max, :validate => :number, :default => 60
+
+  # The number of log entries that have to be processed before
+  # the retry interval is reset to retry_initial.
+  config :retry_reset, :validate => :number, :default => 20
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: Resetting the retry interval to the initial value after a certain number of iterations is not a pattern I have seen before. What's the rationale?

I don't think the description of the option is clear to people. Suggestion: "The number of errors that can occur before the retry interval is reset to `retry_interval`."

**Review by magnusbaeck — CHANGES_REQUESTED** [review]
Apart from the inline comments that I'd like to talk about, the documentation in [master/docs/index.asciidoc](https://github.com/logstash-plugins/logstash-input-websocket/blob/master/docs/index.asciidoc) also needs to be updated. Previously the plugin documentation was generated from the comments in the code but nowadays it's maintained in separate files.

(I mistakenly added a couple of comments as single comments. They should've been part of the review.)

File: lib/logstash/inputs/websocket.rb (hunk 1 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: To avoid log spam when EOF is encountered its debug not warn. In our case that significantly reduced the amount of useless logging in normal operation.

File: lib/logstash/inputs/websocket.rb (hunk 2 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: We have it set to false as we expect 404 in normal operation i.e. the services are only there and listening when needed. This felt like a relatively special case hence the config option, defaulted to true to warn.

File: lib/logstash/inputs/websocket.rb (hunk 3 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: Thanks, its been a loooong time since I did ruby ;-)

File: lib/logstash/inputs/websocket.rb (hunk 4 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: The backoff is there to ensure the service we're connecting to has chance to recover, however we don't want backoff to be permanent. Once we've successfully reconnected and processed some entries (`retry_rest`) the `interval` gets reset so we can quickly recover from a small interruptions.

File: lib/logstash/inputs/websocket.rb (hunk 1 above)
Comment (magnusbaeck) [reply lib/logstash/inputs/websocket.rb]: Oh dear, I totally missed the debug vs. warn difference despite comparing the two calls several times. Yes, it makes sense to not spam about closed connections.

Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: Easy to miss, hopefully I've addressed all your other feedback too, but if I did miss anything just let me know.

File: lib/logstash/inputs/websocket.rb (hunk 4 above)
Comment (magnusbaeck) [reply lib/logstash/inputs/websocket.rb]: I see. But why not just reset the backoff interval as soon as we've reconnected and processed a single message?

File: lib/logstash/inputs/websocket.rb (hunk 2 above)
Comment (magnusbaeck) [reply lib/logstash/inputs/websocket.rb]: In that case, how about instead adding an array option that lists which response codes should be ignored? The default would probably be empty but you could set it to `[404]`. That'd be more generic and, IMHO, easier to understand than a very specific option like `warn_404`.

File: docs/index.asciidoc [hunk 5]
```diff
@@ -33,6 +33,10 @@ This plugin supports the following configuration options plus the <<plugins-{typ
 |Setting |Input type|Required
 | <<plugins-{type}s-{plugin}-mode>> |<<string,string>>, one of `["client"]`|No
 | <<plugins-{type}s-{plugin}-url>> |<<string,string>>|Yes
+| <<plugins-{type}s-{plugin}-retry_initial>> |<<number,number>>|No
+| <<plugins-{type}s-{plugin}-retry_max>> |<<number,number>>|No
+| <<plugins-{type}s-{plugin}-retry_reset>> |<<number,number>>|No
+| <<plugins-{type}s-{plugin}-warn_404>> |<<boolean,boolean>>|No
```
Comment (magnusbaeck) [inline docs/index.asciidoc]: Maintain alphabetical order of options to make navigation easier?

File: lib/logstash/inputs/websocket.rb [hunk 6]
```diff
@@ -13,32 +12,111 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
+
+  # The number of log entries that have to be processed before
+  # the retry interval is reset to retry_initial. This allows
+  # connections to quickly recover from a small interruption
+  # after we have successfully connected and processed some
+  # entries.
+  config :retry_reset, :validate => :number, :default => 20
+
+  # Logs 404 responses as warnings if true otherwise as debug.
+  config :warn_404, :validated => :boolean, :default => true
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: s/validated/validate/

**Review by magnusbaeck — CHANGES_REQUESTED** [review]
Sorry for the slow review. I found a few documentation nits, not terribly important but trivial to address, and I'm still not convinced by some of the proposed configuration options.

File: lib/logstash/inputs/websocket.rb (hunk 4 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: If the service has an issue it may be able to connect and process a single message before failing again, so wanted a little more control over it than that.

Happy to have this default to 1, if you think that's better?

File: lib/logstash/inputs/websocket.rb (hunk 2 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: nice idea, will do.

File: lib/logstash/inputs/websocket.rb (hunk 4 above)
Comment (magnusbaeck) [reply lib/logstash/inputs/websocket.rb]: Okay. Let's keep it configurable but default to one.

File: lib/logstash/inputs/websocket.rb [hunk 7]
```diff
@@ -13,32 +12,112 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
+  # The number of log entries that have to be processed before
+  # the retry interval is reset to retry_initial. This allows
+  # connections to quickly recover from a small interruption
+  # after we have successfully connected and processed some
+  # entries.
+  config :retry_reset, :validate => :number, :default => 1
+
+  # Logs responses with the given HTTP status codes as debug instead
+  # of warning.
+  config :debug_status, :default => [404]
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: Add `:validate => :array`? (And change default value to empty array as per other discussion thread.)

File: lib/logstash/inputs/websocket.rb [hunk 8]
```diff
@@ -13,32 +12,112 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
...
   # is supported, i.e. this plugin connects to a websocket server and
   # receives events from the server as websocket messages.
   config :mode, :validate => ["client"], :default => "client"
 
   def register
     require "ftw"
+    require "uri"
+
+    p = URI.parse(@url)
+    if p.userinfo != ""
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: FWICT p.userinfo is nil if no credentials are provided so this should rather be:

    unless p.userinfo.nil?

As it stands we're adding "***:***" to the URL even if no credentials are provided which makes the log message confusing.

**Review by magnusbaeck — CHANGES_REQUESTED** [review]
Sorry, just a few more things.

**Comment by stevenh** [comment]
@magnusbaeck does this address all your concerns?

File: lib/logstash/inputs/websocket.rb [hunk 9]
```diff
@@ -27,7 +27,7 @@ class LogStash::Inputs::Websocket < LogStash::Inputs::Base
 
   # Logs responses with the given HTTP status codes as debug instead
   # of warning.
-  config :debug_status, :default => [404]
+  config :debug_status, :valdate => :array, :default => []
```
Comment (magnusbaeck) [inline lib/logstash/inputs/websocket.rb]: s/valdate/validate/

**Comment by magnusbaeck** [comment]
Sorry, I've been very busy with other things this week. There's a small but significant typo in the last commit but otherwise we're good.

File: lib/logstash/inputs/websocket.rb (hunk 9 above)
Comment (stevenh) [reply lib/logstash/inputs/websocket.rb]: Doh, fixed

**Comment by stevenh** [comment]
No problem, totally appreciate that.

Typo fixed LMK if there's anything else as keen to get this closed out.

**Review by magnusbaeck — APPROVED** [review]

**Comment by magnusbaeck** [comment]
Merged. Thanks for your patience! Unfortunately it turns out I lack permissions to publish the gem to rubygems.org, but I hope that'll get resolved during Monday.
